version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    environment:
      - PYTHONPATH=/root/src
      - ENV=LOCAL
      - PROJECT_ID=keiba-ds
      - TABLE_ID=test.test
      - KEY_PATH=keiba-ds-project-857126484f5b.json