version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    environment:
      - PYTHONPATH=/root/src
      - BIGQUERY_CREDENTIALS_PATH = keiba-ds-project-857126484f5b.json
