version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - TABLE_ID=${TABLE_ID}
      - DATASET_ID=${DATASET_ID}
      - TEST_TABLE_ID=${TEST_TABLE_ID}
      - TEST_DATASET_ID=${TEST_DATASET_ID}
      - TEST_YEAR=${TEST_YEAR}
      - TEST_MONTH=${TEST_MONTH}
      - TEST_START_DATE=${TEST_START_DATE}
      - TEST_END_DATE=${TEST_END_DATE}
      - TEST_DELETE_DATE=${TEST_DELETE_DATE}
      - MY_KEY_PATH=${MY_KEY_PATH}
      - KEY_PATH=${KEY_PATH}
      - ENV=${ENV}
      - PORT=${PORT}
      - PYTHONPATH=${PYTHONPATH}
      - CREDENTIAL_NOTATION=${CREDENTIAL_NOTATION}
      - GCP_CREDENTIAL_TYPE=${GCP_CREDENTIAL_TYPE}
      - GCP_CREDENTIAL_PROJECT_ID=${GCP_CREDENTIAL_PROJECT_ID}
      - GCP_CREDENTIAL_PRIVATE_KEY_ID=${GCP_CREDENTIAL_PRIVATE_KEY_ID}
      - GCP_CREDENTIAL_PRIVATE_KEY=${GCP_CREDENTIAL_PRIVATE_KEY}
      - GCP_CREDENTIAL_CLIENT_EMAIL=${GCP_CREDENTIAL_CLIENT_EMAIL}
      - GCP_CREDENTIAL_CLIENT_ID=${GCP_CREDENTIAL_CLIENT_ID}
      - GCP_CREDENTIAL_AUTH_URI=${GCP_CREDENTIAL_AUTH_URI}
      - GCP_CREDENTIAL_TOKEN_URI=${GCP_CREDENTIAL_TOKEN_URI}
      - GCP_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL=${GCP_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL}
      - GCP_CREDENTIAL_CLIENT_X509_CERT_URL=${PROJECT_ID}
    restart: always
    tty: true
    ports:
      - 8080:8080